# Server config
server:
    port: 8080

# App config
app:
    cors:
        allowed-origins:
            - "http://localhost:5173"
            - "http://localhost:3000"
            - "http://localhost:3090"
            - "http://127.0.0.1:5500"
    jwt:
        secret-key: "1234567890123456789012345678901234567890" # (Ít nhất 32 ký tự / 256-bit cho thuật toán HS256)
        access-token-expiration-ms: 3600000 # 1 hour
        refresh-token-expiration-ms: 604800000 # 7 days

# Spring config
spring:
    application:
        name: spring_app

    datasource:
        url: jdbc:h2:file:./data/minimal_db;AUTO_SERVER=TRUE
        driverClassName: org.h2.Driver
        username: sa
        password:

    h2:
        console:
            enabled: true
            path: /h2-console

    flyway:
        enabled: true

    thymeleaf:
        cache: false

    jpa:
        show-sql: true
        hibernate:
            # ddl-auto: create
            ddl-auto: validate
        properties:
            hibernate:
                "[format_sql]": true
                "[highlight_sql]": true

    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB

    jackson:
        serialization:
            indent-output: true

    threads:
        virtual:
            enabled: true

# Swagger
springdoc:
    swagger-ui:
        path: /swagger-ui.html

# Logger
logging:
    level:
        "[org.hibernate.SQL]": DEBUG
        "[org.hibernate.orm.jdbc.bind]": TRACE

        "[org.springframework.jdbc.core]": DEBUG
        "[java.sql.Connection]": TRACE
        "[java.sql]": TRACE

org:
    jobrunr:
        background-job-server:
            enabled: true
        dashboard:
            enabled: true
            port: 8000
